before_script: npm install
script: npm run deploy
language: node_js
node_js:
- '6'
branches:
  only:
  - deploy
env:
  global:
  - GH_REF: github.com/hwkr/PlzTeachMe
  - secure: nmcPVIeUjM6BttyN5OATqFp8DHK0i7CPd7bJ1PoYMBv5yTsuqDlqHOD1xOGvKVivQGDetVTnxLqzNzDsmoeSmQfjy/s25GKkZtsUQkAbC/2TMOTpHsV43LrzGrOHIel4pgEYxpJrazSh21tF1QgSPli7xXrSuROsI9YFdTpf1H+UOIp1KG75JCh6Jug2VAPWys64ZSO4D5SgE/ctR7qlo1t5NicZjZ6URq4z20qogQe8I6xJ69bg3eNZDnzWrDvzjOIYH1cBdkMV8sSIsv4K5oeQyOaob1ipJ24+JWBHxIDk+PJzFqO+j7LwdXSoGXpLrDLA/GfwPjyukmG/IDPjiZaUxUc6V2imjqy71P827C0+SnuVY91MVXZy87cfn4bu+ag2yPnOBx+qBT3fYAQ4VSXuIaNIvFfXg697Fvvy01fI41M/NVsPBmBHRCBoZqDA1DJvBt3pLfY9euLXyqw55fiuzRoAS0tuN5T/uZOXSkBCR/gdy0c9wlaLG89wTkAMfuPrWEU6nr+HfgoNg/W/Va7ASqjS+SkTJZJqYy/Ri9WnzfyotSqDq9QAVBWybccK9Xn71e9ZcW0r0N72Z8fqxI1BrUMUA2Vie41en7DiaBXv983dD83hyhsow4P1E8EUmeZIJBupTPhqyDMQKjj0rkOwmSD1tlnYv8XEHPr6oto=
